version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 10
  pre_build:
    commands:
      - rbenv install 2.7.4 && rbenv global 2.7.4
      - bundle install
      - bundle exec rake webpacker:yarn_install
  build:
    commands:
      - echo Build Start
      # - bundle exec rake assets:precompile RAILS_ENV=production
      - bundle exec rspec ./spec/system/post_spec.rb
artifacts:
  files:
    - ./**/*